name: fluchart
description: Charts-Flutter Demo

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  charts_flutter: ^0.8.0
  http: ^0.12.0+2
  flutter_bloc: ^6.0.0
  shared_preferences: ^0.5.3+4
  
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

  meta: ^1.1.1
  intl: ^0.15.2

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/charts-icon.jpg"

flutter:
  uses-material-design: true

  assets:
  
  - assets/